# Generated by Django 5.0.1 on 2024-03-07 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="dbo",
            new_name="dob",
        ),
    ]
